# Generated by Django 3.0 on 2019-12-15 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Some flex points to keep you safe, traveler', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Flex points', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='users_purchased',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
